### PR TITLE
Update AWS.php

### PR DESCRIPTION
**Pull request by kapierstau**
Fixed region for EU endpoint

### CODE REVIEW

**Comment by gullevek** [comment]
Thank you

**Comment by kapierstau** [comment]
Naa, thank you! Saved me a lot of time <3

**Comment by kapierstau** [comment]
Uh btw, do you know when it will be available via composer?

**Comment by gullevek** [comment]
I just pushed v1.2.3 up with this fix

**Comment by kapierstau** [comment]
Perfect, thank you very much.

**Pull request merged**
